on:
  pull_request:
    branches: [main]

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
      ENV: ${{ steps.variables.outputs.ENV }}
      VERSION: ${{ steps.variables.outputs.VERSION }}
      DEPLOYMENT_REF: ${{ steps.variables.outputs.DEPLOYMENT_REF }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          matrix: true
          dir_names: true
          dir_names_max_depth: 1
          files: |
            triton-server**/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - id: variables
        run: |
          echo $GITHUB_OUTPUT
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "ENV=stage" >> $GITHUB_OUTPUT
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "DEPLOYMENT_REF=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else 
            echo "ENV=qa" >> $GITHUB_OUTPUT
            echo "VERSION=$(echo "${{ github.ref_name }}-${GITHUB_SHA:0:7}" )" >> $GITHUB_OUTPUT
            echo "DEPLOYMENT_REF=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT
      # - uses: cake-digital-bank/reuse-workflow/.github/actions/build-and-push@main
      #   with:
      #     version: ${{ steps.variables.outputs.VERSION }}
  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.files }}
          echo ${{ needs.changed-files.outputs.ENV }}
          echo ${{ needs.changed-files.outputs.VERSION }}
          echo ${{ needs.changed-files.outputs.DEPLOYMENT_REF }}