name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          matrix: true
          dir_names: true
          dir_names_max_depth: 1
          files: |
            triton-server**/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'